/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Petra2_client;

import java.net.*;
import java.io.*; 
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author jerem
 */
public class Petra_MainWindow extends javax.swing.JFrame {
    Socket cliSock = null; /* Initialisations indispensables */
    DataInputStream dis=null;
    DataOutputStream dos=null; 
    String IP = "192.168.1.29"; int port = 40004;
	//thread_Capteurs thread=null;
	private Thread internalThread;
    
    /**
     * Creates new form Petra_MainWindow
     */
    public Petra_MainWindow() 
	{
        initComponents();
        this.jLabel_recu.setText("");
        this.jLabel_envoye.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup_capteurs = new javax.swing.ButtonGroup();
        jPanel_picture = new javax.swing.JPanel();
        jLabel_petra = new javax.swing.JLabel();
        jPanel_actuateurs = new javax.swing.JPanel();
        jLabel_actuateurs = new javax.swing.JLabel();
        jRadioButtonConv1 = new javax.swing.JRadioButton();
        jRadioButtonConv2 = new javax.swing.JRadioButton();
        jRadioButtonPlongeur = new javax.swing.JRadioButton();
        jRadioButtonVentouse = new javax.swing.JRadioButton();
        jRadioButtonBras = new javax.swing.JRadioButton();
        jRadioButtonGrappin = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel_capteurs = new javax.swing.JPanel();
        jLabel_capteurs = new javax.swing.JLabel();
        jCheckBox_L1 = new javax.swing.JCheckBox();
        jCheckBox_L2 = new javax.swing.JCheckBox();
        jCheckBox_T = new javax.swing.JCheckBox();
        jCheckBox_S = new javax.swing.JCheckBox();
        jCheckBox_CS = new javax.swing.JCheckBox();
        jCheckBox_H = new javax.swing.JCheckBox();
        jCheckBox_AP = new javax.swing.JCheckBox();
        jCheckBox_PP = new javax.swing.JCheckBox();
        jCheckBox_DE = new javax.swing.JCheckBox();
        jPanel_connection = new javax.swing.JPanel();
        jLabel_recutext = new javax.swing.JLabel();
        jLabel_envoyetext = new javax.swing.JLabel();
        jLabel_recu = new javax.swing.JLabel();
        jLabel_envoye = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_serverIP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_serverPort = new javax.swing.JTextField();
        jButton_connect = new javax.swing.JButton();
        jButton_Deconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_picture.setAlignmentY(0.0F);

        jLabel_petra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petra2_client/petra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_pictureLayout = new javax.swing.GroupLayout(jPanel_picture);
        jPanel_picture.setLayout(jPanel_pictureLayout);
        jPanel_pictureLayout.setHorizontalGroup(
            jPanel_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(jPanel_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_pictureLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_petra)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel_pictureLayout.setVerticalGroup(
            jPanel_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(jPanel_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_pictureLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_petra)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel_actuateurs.setText("Actuateurs");

        buttonGroup1.add(jRadioButtonConv1);
        jRadioButtonConv1.setText("Convoyeur 1");
        jRadioButtonConv1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonConv1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonConv2);
        jRadioButtonConv2.setText("Convoyeur 2");
        jRadioButtonConv2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonConv2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPlongeur);
        jRadioButtonPlongeur.setText("Plongeur");
        jRadioButtonPlongeur.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonPlongeurActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonVentouse);
        jRadioButtonVentouse.setText("Ventouse");
        jRadioButtonVentouse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonVentouseActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBras);
        jRadioButtonBras.setText("Bras");
        jRadioButtonBras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonBrasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonGrappin);
        jRadioButtonGrappin.setText("Grappin");
        jRadioButtonGrappin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonGrappinActionPerformed(evt);
            }
        });

        jLabel8.setText("Chariot");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Réservoir", "Convoyeur 1", "Bac KO", "Convoyeur 2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_actuateursLayout = new javax.swing.GroupLayout(jPanel_actuateurs);
        jPanel_actuateurs.setLayout(jPanel_actuateursLayout);
        jPanel_actuateursLayout.setHorizontalGroup(
            jPanel_actuateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_actuateursLayout.createSequentialGroup()
                .addGroup(jPanel_actuateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_actuateurs)
                    .addGroup(jPanel_actuateursLayout.createSequentialGroup()
                        .addComponent(jRadioButtonConv1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonConv2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPlongeur)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonVentouse)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonGrappin)
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButtonBras)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_actuateursLayout.setVerticalGroup(
            jPanel_actuateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_actuateursLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_actuateurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_actuateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_actuateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_actuateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonConv1)
                        .addComponent(jRadioButtonConv2)
                        .addComponent(jRadioButtonPlongeur)
                        .addComponent(jRadioButtonVentouse)
                        .addComponent(jRadioButtonBras)
                        .addComponent(jRadioButtonGrappin)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel_capteurs.setText("Capteurs");

        buttonGroup_capteurs.add(jCheckBox_L1);
        jCheckBox_L1.setText("L1");

        buttonGroup_capteurs.add(jCheckBox_L2);
        jCheckBox_L2.setText("L2");

        buttonGroup_capteurs.add(jCheckBox_T);
        jCheckBox_T.setText("T");

        buttonGroup_capteurs.add(jCheckBox_S);
        jCheckBox_S.setText("S");

        buttonGroup_capteurs.add(jCheckBox_CS);
        jCheckBox_CS.setText("CS");

        buttonGroup_capteurs.add(jCheckBox_H);
        jCheckBox_H.setText("H");

        buttonGroup_capteurs.add(jCheckBox_AP);
        jCheckBox_AP.setText("AP");

        buttonGroup_capteurs.add(jCheckBox_PP);
        jCheckBox_PP.setText("PP");

        buttonGroup_capteurs.add(jCheckBox_DE);
        jCheckBox_DE.setText("DE");

        javax.swing.GroupLayout jPanel_capteursLayout = new javax.swing.GroupLayout(jPanel_capteurs);
        jPanel_capteurs.setLayout(jPanel_capteursLayout);
        jPanel_capteursLayout.setHorizontalGroup(
            jPanel_capteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_capteursLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel_capteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_capteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_L1)
                        .addComponent(jCheckBox_T)
                        .addComponent(jCheckBox_S)
                        .addComponent(jCheckBox_CS)
                        .addComponent(jCheckBox_H)
                        .addComponent(jCheckBox_AP)
                        .addComponent(jCheckBox_PP)
                        .addComponent(jCheckBox_DE)
                        .addComponent(jCheckBox_L2))
                    .addComponent(jLabel_capteurs))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel_capteursLayout.setVerticalGroup(
            jPanel_capteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_capteursLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_capteurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_L2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_T)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_S)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_CS)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_H)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_AP)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_PP)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_DE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_recutext.setText("Reçu:");

        jLabel_envoyetext.setText("Envoyé:");

        jLabel_recu.setText("[data]");

        jLabel_envoye.setText("[data]");

        jLabel6.setText("IP serveur:");

        jTextField_serverIP.setText("192.168.1.29");
        jTextField_serverIP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTextField_serverIPFocusLost(evt);
            }
        });

        jLabel7.setText("Port:");

        jTextField_serverPort.setText("40004");
        jTextField_serverPort.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTextField_serverPortFocusLost(evt);
            }
        });

        jButton_connect.setText("Connexion au serveur");
        jButton_connect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_connectActionPerformed(evt);
            }
        });

        jButton_Deconnexion.setText("Déconnexion");
        jButton_Deconnexion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_DeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_connectionLayout = new javax.swing.GroupLayout(jPanel_connection);
        jPanel_connection.setLayout(jPanel_connectionLayout);
        jPanel_connectionLayout.setHorizontalGroup(
            jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_connectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_connect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jButton_Deconnexion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_connectionLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_connectionLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_connectionLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_serverIP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_serverPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_connectionLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_recutext)
                        .addComponent(jLabel_envoyetext)
                        .addComponent(jLabel_recu)
                        .addComponent(jLabel_envoye))
                    .addContainerGap(164, Short.MAX_VALUE)))
        );
        jPanel_connectionLayout.setVerticalGroup(
            jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_connectionLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_serverIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jButton_connect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Deconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_connectionLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel_recutext)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel_recu)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel_envoyetext)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel_envoye)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_actuateurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_capteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_actuateurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_capteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connectActionPerformed
        try
        {
            cliSock = new Socket(IP, port);
            System.out.println(cliSock.getInetAddress().toString());
            dis = new DataInputStream(cliSock.getInputStream());
            dos = new DataOutputStream(cliSock.getOutputStream());
			//thread = new thread_Capteurs(dis); thread.start();
			// lancer le thread/bean des capteurs
			Runnable r = new Runnable()
			{
				public void run()
				{
					try
					{
						runWork();
					}
					catch (Exception e)
					{
						System.err.println(e.getMessage());
					}
				}
			};
			internalThread = new Thread(r, "Thread capteurs");
			internalThread.start();
        }
        catch (UnknownHostException e)
        {
            System.err.println("Erreur ! Host non trouvé [" + e + "]");
        }
        catch (IOException e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e + "]");
        } 
    }//GEN-LAST:event_jButton_connectActionPerformed

    private void jRadioButtonConv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConv1ActionPerformed
        try
        {
            sendMsg(1);
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jRadioButtonConv1ActionPerformed

    private void jRadioButtonConv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConv2ActionPerformed
        try
        {
            sendMsg(2);
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jRadioButtonConv2ActionPerformed

    private void jRadioButtonPlongeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPlongeurActionPerformed
        try
        {
            sendMsg(4);
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jRadioButtonPlongeurActionPerformed

    private void jRadioButtonVentouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVentouseActionPerformed
        try
        {
            sendMsg(3);
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jRadioButtonVentouseActionPerformed

    private void jRadioButtonBrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBrasActionPerformed
        try
        {
            sendMsg(5);
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jRadioButtonBrasActionPerformed

    private void jRadioButtonGrappinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGrappinActionPerformed
        try
        {
            sendMsg(6);
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jRadioButtonGrappinActionPerformed

    private void jTextField_serverIPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_serverIPFocusLost
        try
        {
            IP = this.jTextField_serverIP.getText();
            System.out.println("IP: " + IP);
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jTextField_serverIPFocusLost

    private void jTextField_serverPortFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_serverPortFocusLost
        try
        {
            port = Integer.valueOf(this.jTextField_serverPort.getText());
            System.out.println("Port: " + port);
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jTextField_serverPortFocusLost

    private void jButton_DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeconnexionActionPerformed
        try
        {
            sendMsg(0);
			internalThread.interrupt();
			dis.close();
			dos.close();
			cliSock.close();
			internalThread.stop();
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jButton_DeconnexionActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int choice;
        System.out.println("test");
        try
        {
            buttonGroup1.clearSelection();
            choice = jComboBox1.getSelectedIndex();
            System.out.println("Choix: " + choice);
            switch(choice)
            {
                case 0: sendMsg(7); break;
                case 1: sendMsg(8); break;
                case 2: sendMsg(9); break;
                case 3: sendMsg(10); break;
            }
        }
        catch(Exception e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e.getMessage() + "]");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void sendMsg(int num)
    {
        try
        {
            this.jLabel_envoye.setText(String.valueOf(num));
            //dos.write(num.getBytes()); dos.flush();
            dos.writeByte(num); dos.flush();
        }
        catch (IOException e)
        {
            System.err.println("Erreur de communication ? [" + e + "]");
        }
    }
    
	private void runWork()
	{
		byte capteur, old_value = 0;
		
		System.out.println("Démarrage thread...");
		while(true)
		{
			try
			{
				capteur = dis.readByte();
				System.out.println("Recu: " + capteur);
				if(capteur != old_value)
				{
					this.buttonGroup_capteurs.clearSelection();
					switch(capteur)
					{
						case 0:
							System.out.println("L1");
							this.jCheckBox_L1.setSelected(true);
							break;
						case 1:
							System.out.println("L2");
							this.jCheckBox_L2.setSelected(true);
							break;
						case 2:
							System.out.println("T - Epaisseur");
							this.jCheckBox_T.setSelected(true);
							break;
						case 3:
							System.out.println("S - Slot");
							this.jCheckBox_L1.setSelected(true);
							break;
						case 4:
							System.out.println("CS - Chariot Stable");
							this.jCheckBox_L1.setSelected(true);
							break;
						case 5:
							System.out.println("AP - Bras");
							this.jCheckBox_AP.setSelected(true);
							break;
						case 6:
							System.out.println("PP - Plongeur");
							this.jCheckBox_PP.setSelected(true);
							break;
						case 7:
							System.out.println("DE - Bac d'entrée");
							this.jCheckBox_DE.setSelected(true);
							break;
						default:
							break;
					}
					old_value = capteur;
				}
			}
			catch (IOException e) 
			{
				System.err.println("readByte Error: " + e.getMessage());
			}
			catch (Exception e)
			{
				System.err.println("readByte Error: " + e.getMessage());
			}
		}
	}
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petra_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petra_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petra_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petra_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Petra_MainWindow().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup_capteurs;
    private javax.swing.JButton jButton_Deconnexion;
    private javax.swing.JButton jButton_connect;
    private javax.swing.JCheckBox jCheckBox_AP;
    private javax.swing.JCheckBox jCheckBox_CS;
    private javax.swing.JCheckBox jCheckBox_DE;
    private javax.swing.JCheckBox jCheckBox_H;
    private javax.swing.JCheckBox jCheckBox_L1;
    private javax.swing.JCheckBox jCheckBox_L2;
    private javax.swing.JCheckBox jCheckBox_PP;
    private javax.swing.JCheckBox jCheckBox_S;
    private javax.swing.JCheckBox jCheckBox_T;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_actuateurs;
    private javax.swing.JLabel jLabel_capteurs;
    private javax.swing.JLabel jLabel_envoye;
    private javax.swing.JLabel jLabel_envoyetext;
    private javax.swing.JLabel jLabel_petra;
    private javax.swing.JLabel jLabel_recu;
    private javax.swing.JLabel jLabel_recutext;
    private javax.swing.JPanel jPanel_actuateurs;
    private javax.swing.JPanel jPanel_capteurs;
    private javax.swing.JPanel jPanel_connection;
    private javax.swing.JPanel jPanel_picture;
    private javax.swing.JRadioButton jRadioButtonBras;
    private javax.swing.JRadioButton jRadioButtonConv1;
    private javax.swing.JRadioButton jRadioButtonConv2;
    private javax.swing.JRadioButton jRadioButtonGrappin;
    private javax.swing.JRadioButton jRadioButtonPlongeur;
    private javax.swing.JRadioButton jRadioButtonVentouse;
    private javax.swing.JTextField jTextField_serverIP;
    private javax.swing.JTextField jTextField_serverPort;
    // End of variables declaration//GEN-END:variables
}
